### ISSUE TITLE
Hidden internal errors

### ISSUE THREAD

**Issue by PSF1** [jcraane/gpt-mentor-plugin#16]
Hi,

I don't know why but I found two errors in the background:

![imagen](https://user-images.githubusercontent.com/10193279/230906564-9eb502af-f77e-4d48-87c1-98fed5ef1ee3.png)

```
java.lang.Throwable: null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:206)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at dev.jamiecraane.gptmentorplugin.openapi.ChatGptEventSourceListener.onFailure(ChatGptEventSourceListener.kt:31)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:52)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

![imagen](https://user-images.githubusercontent.com/10193279/230906704-19fb1409-d1e7-488c-a4f2-dc1d68b94434.png)

```
java.lang.Throwable: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:206)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at dev.jamiecraane.gptmentorplugin.openapi.ChatGptEventSourceListener.onFailure(ChatGptEventSourceListener.kt:31)
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:78)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Today I got some context window errors, maybe that have a relation with these errors.

**Comment by PSF1** [comment]
I'm sorry, I don't know.
